### ISSUE TITLE
Input field should be a Date Picker and Time Picker

### ISSUE THREAD

**Issue by stbensonimoh** [anyanime/rccgfols-reception-form#5]
![image](https://user-images.githubusercontent.com/24779836/101290571-755cb780-3803-11eb-849a-ba27b7a2de9d.png)

- [ ] Label should read:

> When would you be available for a visit
instead.
- [ ] The input field should be a date picker and time picker.

**Comment by jveer634** [comment]
@stbensonimoh Can you be a little more specific about the details of the input field that you're referring to..

**Comment by stbensonimoh** [comment]
> @stbensonimoh Can you be a little more specific about the details of the input field that you're referring to..

We want to know the perfect time to pay the member a visit at home. It is common knowledge that when users see a **text input** field, they can type in anything. So it is better to use radio buttons, checkboxes and other input types that require less user typing.
I suggest that instead of the text input field, a **date picker** and a **time picker** should be used.
The `<input type="datetime-local">` HTML tag should be used. See example below:
```
<label for="birthdaytime">Birthday (date and time):</label>
<input type="datetime-local" id="birthdaytime" name="birthdaytime">
```

**Comment by jveer634** [comment]
I've made the changes and made a pr but the netlify checks are not satisfied.

**Comment by stbensonimoh** [comment]
@jveer634 Thanks for the PR. I left some comments. Kindly effect and merge. Thanks. :+1:
